---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

 

  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Show management
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/setting/management
        cmd: 'show'
      register: management

    - debug: msg="{{ management.stdout }}"

    - name: Enable Logon High DP Load Box
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/setting/management
        element: '<enable-log-high-dp-load>yes</enable-log-high-dp-load>'

    - name: Commit configuration
      panos_commit_firewall:
        provider: '{{ provider }}'

####after

    - name: Show management
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/setting/management
        cmd: 'show'
      register: management2

    - debug: msg="{{ management2.stdout }}"

    - name: Successfully enabled high dp load
      debug: msg="High DP Load enabled"
      when: management.stdout != management2.stdout

    - debug: msg="No changes made"
      when: management.stdout == management2.stdout
...