---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

 
  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Enable ssh, http and snmp
      panos_management_profile:
        provider: '{{ provider }}'
        name: '{{ item.name }}'
        ssh: true
        https: true
        snmp: true
        permitted_ip:
          - '122.128.123.110'
          - '112.118.132.71'
          - '172.21.254.132'
          - '172.21.214.121'
          - '12.28.254.134'
          - '12.28.254.130'
          - '17.28.200.48'
          - '72.28.200.70'
          - '12.18.200.70'  
      loop:
        - { name: Interface Management }
        #- { name: Interface names }
        #- { name: Interface names }

    - name: Show interface management
      panos_type_cmd:
        provider: '{{ provider }}'
        cmd: 'show'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/profiles/interface-management-profile
      register: intmgt
      ignore_errors: yes

    - debug: msg="{{ intmgt }}"

    - name: Commit configuration
      panos_commit_firewall:
        provider: '{{ provider }}'
      ignore_errors: yes

    - name: Show interface management
      panos_type_cmd:
        provider: '{{ provider }}'
        cmd: 'show'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/profiles/interface-management-profile
      register: intmgt2
      ignore_errors: yes

    - debug: msg="{{ intmgt2 }}"

    - name: Success
      debug: msg="Interface management created allows only for SSH, HTTPS and SNMP"
      when: intmgt2 != intmgt

    - name: No changes
      debug: msg="No changes made"
      when: intmgt2 == intmgt
...