---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

 

  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Ensure 'V3' is selected for SNMP polling
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/system/snmp-setting/access-setting
        element: |
          <version>
            <v3>
              <views>
                <entry name="View">
                  <view>
                    <entry name="view">
                      <oid>1</oid>
                      <option>include</option>
                      <mask>0xFFE</mask>
                    </entry>
                  </view>
                </entry>
              </views>
              <users>
                <entry name="<yourusername_sameasinhostsfile">
                  <authpwd>12345678</authpwd>
                  <privpwd>12345678</privpwd>
                  <view>View</view>
                  <authproto>SHA</authproto><privproto>AES</privproto>
                </entry>
              </users>
            </v3>
          </version>
                  
    - name: before commit
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/system/snmp-setting/access-setting
        cmd: 'show'
      register: polling
      ignore_errors: yes

    - name: Commit configuration
      panos_commit_firewall:
        provider: '{{ provider }}'

    - name: after commit
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/system/snmp-setting/access-setting
        cmd: 'show'
      register: polling2

    - debug: msg="{{ polling2 }}"

    - name: Success
      debug: msg="Successfully configured SNMP polling"
      when: polling != polling2

    - name: Success
      debug: msg="No changes made"
      when: polling == polling2

  
...