---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas


  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Ensure redundant NTP servers are configured appropriately
      panos_mgtconfig:
        provider: "{{ provider }}"
        ntp_server_primary: 8.8.8.8
        ntp_server_secondary: 8.8.8.4
      
    - name: Before commit
      panos_type_cmd:
        provider: "{{ provider }}"
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/system/ntp-servers  
        cmd: 'show'    
      register: before
      
      #if ntp isnt changed, it will be empty thus the error. hence ignore_errors is used
    - name: Commit configuration
      panos_commit_firewall:
        provider: "{{ provider }}"
      ignore_errors: yes

    - name: After commit
      panos_type_cmd:
        provider: "{{ provider }}"
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/system/ntp-servers  
        cmd: 'show'    
      register: 'after'

    - debug: msg="{{ after }}"

    - name: Success
      debug: msg="Successfully configured NTP servers"
      when: before != after

    - name: No changes
      debug: msg="No changes made"
      when: before == after
...