---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

  

  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true
  
#    - name: Set HA2 enabled
#      panos_type_cmd:
#        provider: '{{ provider }}'
#        xpath: |
#          /config/devices/entry[@name='localhost.localdomain']
#          /deviceconfig/high-availability
#        element: |
#          <enabled>yes</enabled>
#          <group><group-id>1</group-id></group>
          
    - name: Ensure a fully synchronized High Availability peer is configured
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability/group/state-synchronization
        element: |
          <enabled>yes</enabled>
          <transport>ethernet</transport> #ethernet/ip/udp
    
    - name: Set HA2
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability/interface/ha2
        element: |
          <ip-address>172.18.254.133</ip-address>
          <netmask>255.255.255.252</netmask>
    
    - name: before
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability
        cmd: 'show'
      register: before

    - name: Commit
      panos_commit_firewall:
        provider: '{{ provider }}'
      ignore_errors: yes

    - name: after
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability
        cmd: 'show'
      register: after

    - debug: msg="Successfully configured HA2"
      when: before != after

    - debug: msg="No changes made"
      when: before == after
...