---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

  

  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true
  
    - name: Set passive-link-state auto
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability/group/mode/active-passive
        element: |
          <passive-link-state>auto</passive-link-state>

    - name: Disable Preemptive
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability/group/election-option
        element: |
          <preemptive>no</preemptive>

    - name: before
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability/group/mode/active-passive
        cmd: 'show'
      register: before

    - debug: msg="{{ before }}"

    - name: before1
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability/group/election-option
        cmd: 'show'
      register: before1
    
    - debug: msg="{{ before1 }}"

    - name: Commit
      panos_commit_firewall:
        provider: '{{ provider }}'

    - name: after
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability/group/mode/active-passive
        cmd: 'show'
      register: after

    - debug: msg="{{ after }}"

    - name: after1
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/high-availability/group/election-option
        cmd: 'show'
      register: after1

    - debug: msg="{{ after1 }}"

    - debug: msg="Successfully configured massive link state and preemptive"
      when: before != after or before1 != after1

    - debug: msg="No changes made"
      when: before == after and before1 == after1
...