---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas



  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Ensure that wildfire file size upload limits are maximized (PE)
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting/wildfire/file-size-limit
        element: |
          <entry name="pe"><size-limit>50</size-limit></entry>
          <entry name="apk"><size-limit>50</size-limit></entry>
          <entry name="pdf"><size-limit>51200</size-limit></entry>
          <entry name="ms-office"><size-limit>51200</size-limit></entry>
          <entry name="jar"><size-limit>20</size-limit></entry>
          <entry name="flash"><size-limit>10</size-limit></entry>
          <entry name="MacOSX"><size-limit>50</size-limit></entry>
          <entry name="archive"><size-limit>50</size-limit></entry>
          <entry name="linux"><size-limit>50</size-limit></entry>
          <entry name="script"><size-limit>4096</size-limit></entry>

    - name: beforesize
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting/wildfire/file-size-limit
        cmd: 'show'
      register: size
      ignore_errors: yes

    #- debug: msg="{{ size.stdout }}"

    - name: Commit configuration
      panos_commit_firewall:
        provider: "{{ provider }}"

    - name: aftersize
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting/wildfire/file-size-limit
        cmd: 'show'
      register: size2
      ignore_errors: yes
      
    #- debug: msg="{{ size2.stdout }}"


    - debug: msg="Wildfire upload size are configured succesfully"
      when: size != size2

    - debug: msg="No changes made"
      when: size == size2
...