---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

 

  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Ensure alerts are enabled for malicious files detected by WildFire
      panos_log_forwarding_profile_match_list:
        provider: '{{ provider }}'
        log_forwarding_profile: 'Log Forwarding Profile'
        name: 'Log Match List'
        description: 'A log forwarding profile'
        log_type: 'wildfire'
        filter: '(verdict neq benign)'
        syslog_profiles: ['Syslog Server Profile'] 
        #only created syslog, if needed create snmp,email and http profiles
        #snmp_profiles: ['SNMP']
        #email_profiles: ['Email']
        #http_profiles: ['HTTP']
         


    - name: Commit configuration
      panos_commit_firewall:
        provider: "{{ provider }}"
...