---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

 

  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Ensure that antivirus profiles are set to block on all decoders except 'imap' and 'pop3'
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/virus/entry[@name='AntivirusProfile']
        cmd: 'set'
        element: |
          <decoder>
            <entry name="ftp">
              <action>drop</action>
              <wildfire-action>drop</wildfire-action>
              <mlav-action>default</mlav-action>
            </entry>

            <entry name="http">
              <action>drop</action>
              <wildfire-action>drop</wildfire-action>
              <mlav-action>default</mlav-action></entry>
            <entry name="http2">
              <action>drop</action>
              <wildfire-action>drop</wildfire-action>
              <mlav-action>default</mlav-action></entry>
            <entry name="imap">
              <action>reset-both</action>
              <wildfire-action>reset-both</wildfire-action>
              <mlav-action>default</mlav-action></entry>
            <entry name="pop3">
              <action>reset-both</action>
              <wildfire-action>reset-both</wildfire-action>
              <mlav-action>default</mlav-action></entry>
            <entry name="smb">
              <action>drop</action>
              <wildfire-action>drop</wildfire-action>
              <mlav-action>default</mlav-action></entry>
            <entry name="smtp">
              <action>drop</action>
              <wildfire-action>drop</wildfire-action>
              <mlav-action>default</mlav-action>
            </entry>
          </decoder>
          <packet-capture>no</packet-capture>
          <mlav-engine-filebased-enabled>
            <entry name="Windows Executables">
              <mlav-policy-action>disable</mlav-policy-action>
            </entry>
            <entry name="PowerShell Script 1">
              <mlav-policy-action>disable</mlav-policy-action>
            </entry>
            <entry name="PowerShell Script 2">
              <mlav-policy-action>disable</mlav-policy-action>
            </entry>
            <entry name="Executable Linked Format">
              <mlav-policy-action>disable</mlav-policy-action>
            </entry>
            <entry name="MSOffice">
              <mlav-policy-action>disable</mlav-policy-action>
            </entry>
          </mlav-engine-filebased-enabled>

    - name: before
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/virus
        cmd: 'show'
      register: before
      ignore_errors: yes

    - name: Commit configuration
      panos_commit_firewall:
        provider: '{{ provider }}'


    - name: after
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/virus
        cmd: 'show'
      register: after

    - debug: msg="Configured antivirus profile successfully"
      when: before != after

    - debug: msg="No changes made"
      when: before == after
...