---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

  
  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Add Data Pattern (CAN BE DELETED SINCE ITS NOT IN CIS)
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/data-objects/entry[@name='DataPattern']
        element: |
          <pattern-type>
            <file-properties>
              <pattern>
                <entry name='pattern'>
                  <file-type>pdf</file-type>
                  <file-property>panav-rsp-pdf-dlp-author</file-property>
                  <property-value>1</property-value>
                </entry>
              </pattern>
            </file-properties>
          </pattern-type>

    - name: datapattern_before
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/data-objects
        cmd: 'show'
      register: datapattern
      ignore_errors: yes

    - name: >
        Ensure that alert after a threshold of credit card or Social
        Security numbers is detected is enabled
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/data-filtering/entry[@name='DataFilteringProfile']
        cmd: 'set'
        element: |
          <rules>
            <entry name="rule0">
              <application><member>any</member></application>
              <file-type><member>any</member></file-type>
              <direction>both</direction>
              <alert-threshold>20</alert-threshold>
              <block-threshold>0</block-threshold>
              <data-object>DataPattern</data-object>
              <log-severity>informational</log-severity>
            </entry>
          </rules>

    - name: data_filterbefore
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/data-filtering
        cmd: 'show'
      register: datafilter
      ignore_errors: yes

    - name: Commit configuration
      panos_commit_firewall:
        provider: '{{ provider }}'

    - name: datapattern_after
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/data-objects
        cmd: 'show'
      register: datapattern2

    - name: data_filterafter
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /profiles/data-filtering
        cmd: 'show'
      register: datafilter2

    - debug: msg="Data Pattern created successfully"
      when: datapattern != datapattern2
    
    - debug: msg="Alert for detection enabled"
      when: datafilter != datafilter2

    - debug: msg="No changes made"
      when: datafilter == datafilter2
...