---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

  

  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: Starting network interface ethernet1/4 for the interface, can be changed
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/interface/ethernet/entry[@name='ethernet1/4']
        element: |
          <link-state>auto</link-state><tap/>

    - name: Create Zone Protection Profile
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/profiles/zone-protection-profile/entry[@name='ZoneProtection']
        cmd: 'set'
        element: |
          <flood>
            <tcp-syn>
              <syn-cookies>
                <alarm-rate>20000</alarm-rate>
                <activate-rate>25000</activate-rate>
                <maximal-rate>1000000</maximal-rate>
              </syn-cookies>
              <enable>yes</enable>
            </tcp-syn>
            <udp>
              <red>
                <alarm-rate>10000</alarm-rate>
                <activate-rate>10000</activate-rate>
                <maximal-rate>40000</maximal-rate>
              </red>
              <enable>no</enable>
            </udp>
            <icmp>
              <red>
                <alarm-rate>10000</alarm-rate>
                <activate-rate>10000</activate-rate>
                <maximal-rate>40000</maximal-rate>
              </red>
              <enable>no</enable></icmp>
            <icmpv6>
              <red>
                <alarm-rate>10000</alarm-rate>
                <activate-rate>10000</activate-rate>
                <maximal-rate>40000</maximal-rate>
              </red>
              <enable>no</enable>
            </icmpv6>
            <other-ip>
              <red>
                <alarm-rate>10000</alarm-rate>
                <activate-rate>10000</activate-rate>
                <maximal-rate>40000</maximal-rate>
              </red>
            <enable>no</enable>
            </other-ip>
          </flood>
          
  
    - name: Create Network Zone
      panos_zone:
        provider: '{{ provider }}'
        zone: 'DMZ'
        mode: 'tap'
        interface: ['ethernet1/4']
        zone_profile: ZoneProtection
          
    - name: before zoneprofilecreation
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/profiles/zone-protection-profile
        cmd: 'show'
      register: before
      ignore_errors: yes

    - name: before zonecreation
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /zone
        cmd: 'show'
      register: before1
      ignore_errors: yes

    - name: Commit configuration
      panos_commit_firewall:
        provider: '{{ provider }}'

    - name: after zonecreation
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/profiles/zone-protection-profile
        cmd: 'show'
      register: after

    - name: after zonecreation
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /zone
        cmd: 'show'
      register: after1

    #- debug: msg="{{ before }}"
    #- debug: msg="{{ after }}"
    #- debug: msg="{{ before1 }}"
    #- debug: msg="{{ after1 }}"

    - debug: msg="Enabled SYN flood action of SYN cookies is attached to all untrusted zones successfully"
      when: before != after or before1 != after1

    - debug: msg="No changes made"
      when: before == after and before1 == after1
...