---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

 
  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: >
        Ensure all zones have Zone Protection Profiles that drop specially
        crafted packets
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/profiles/zone-protection-profile/entry[@name='ZoneProtection']
        cmd: 'set'
        element: |
          <discard-ip-spoof>yes</discard-ip-spoof>
          <discard-strict-source-routing>yes</discard-strict-source-routing>
          <discard-security>no</discard-security>
          <discard-loose-source-routing>yes</discard-loose-source-routing>
          <discard-stream-id>no</discard-stream-id>
          <discard-timestamp>no</discard-timestamp>
          <discard-unknown-option>no</discard-unknown-option>
          <discard-record-route>no</discard-record-route>
          <discard-malformed-option>yes</discard-malformed-option>
          <discard-overlapping-tcp-segment-mismatch>yes</discard-overlapping-tcp-segment-mismatch>

    - name: before
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/profiles/zone-protection-profile
        cmd: 'show'
      register: before
      ignore_errors: yes

    - name: Commit configuration
      panos_commit_firewall:
        provider: '{{ provider }}'

    - name: after
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /network/profiles/zone-protection-profile
        cmd: 'show'
      register: after

    - debug: msg="Successfully configured zone protection profile that drop specially crafted packets"
      when: before != after

    - debug: msg="No changes made"
      when: before == after
...