---
- name: Palo Alto Playbook
  hosts: palo
  gather_facts: false
  connection: local

  collections:
  - paloaltonetworks.panos
  - cyberark.pas

  

  tasks:
  
    - name: credential retrieval
      cyberark.pas.cyberark_credential:
        api_base_url: "<https://cyberark.example.com>"
        validate_certs: "false"
        app_id: "<ansible>"
        aim_object: "<target_system_object_name>"
        reason: "requesting credential for ansible deployment"
        connection_timeout: 60
        query: "Safe=test;UserName=admin"
        query_format: "Exact"
        fail_request_on_password_change: True
      register: ca_cred
      delegate_to: localhost
      no_log: true

    - name: Set ansible_password to remote node
      ansible.builtin.set_fact:
        provider:
          ip_address: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_password: "{{ ca_cred.result.Content }}"
      no_log: true

    - name: >
        Ensure application security policies exist when allowing traffic
        from an untrusted zone to a more trusted zone and ensuring service
        setting of any in a security policy allowing traffic does not exist
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /rulebase/security/rules/entry[@name='Zone Security Policy']
        cmd: 'set'
        element: |
          <to><member>DMZ</member></to>
          <from><member>any</member></from>
          <source><member>any</member></source>
          <destination><member>any</member></destination>
          <source-user><member>any</member></source-user>
          <category><member>any</member></category>
          <application><member>1c-enterprise</member></application>
          <service><member>application-default</member></service>
          <action>deny</action>
    
    - name: before
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /rulebase/security/rules
        cmd: 'show'
      register: before
      ignore_errors: yes

    - name: Commit configuration
      panos_commit_firewall:
        provider: '{{ provider }}'

    - name: after
      panos_type_cmd:
        provider: '{{ provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /vsys/entry[@name='vsys1']
          /rulebase/security/rules
        cmd: 'show'
      register: after

    - debug: msg="zone security policy configured successfully"
      when: before != after

    - debug: msg="No changes made"
      when: before == after
...